version: '2'

services:
  control:
    image: kiwi-control
    build:
      context: .
      dockerfile: Dockerfile.amd64
    network_mode: "host"
    ipc: "host"
    volumes:
      - /tmp:/tmp
    command: "--cid=111 --freq=30 --verbose --steering_gain=1.0 --steering_deadzone=0.05  --max_steering_angle=0.52 --default_pedal_position=0.09 --max_pedal_position=0.12"
